Volatile to atomic
microstream-one/microstream pull request #239
Opened 2021-09-09 09:35 UTC by johny2000uwb

Change all primitivy types with volatile to Atomic types. This should guarantee atomic operations on these variables, reduce the need for synchronized blocks and, most importantly, reduce the possibility of creating errors in the future with respect to synchronization.

It has been tested. By the test shows this solution a slightly better performance.

2021-09-14 08:30 UTC, hg-ms approved these changes

2021-09-15 08:26 UTC, fh-ms requested changes

2021-09-15 08:26 UTC, fh-ms commented on base/src/main/java/one/microstream/concurrency/Threaded.java
>  		// increase size and rebuild slots array if necessary
This must be `getAndIncrement()`

2021-09-15 08:39 UTC, johny2000uwb commented on base/src/main/java/one/microstream/concurrency/Threaded.java
>  		// increase size and rebuild slots array if necessary
yes, you right. ++size and size++

2021-09-15 13:27 UTC, fh-ms approved these changes

2021-09-15 13:38 UTC, merged