Doc update
microstream-one/microstream pull request #452
Opened 2022-09-28 09:47 UTC by fh-ms

Update some Javadoc.
Add missing documentation for some connectors #443

2022-09-28 09:47 UTC, fh-ms commented
@hg-ms maybe we should tackle #304 in this pr as well

2022-09-28 11:04 UTC, hg-ms requested changes

2022-09-28 11:04 UTC, hg-ms commented on docs/modules/storage/pages/storage-targets/blob-stores/google-cloud-firestore.adoc
> +|Tets the emulator host to use with this Firestore client.
Typo?

2022-09-28 11:34 UTC, fh-ms commented on docs/modules/storage/pages/storage-targets/blob-stores/google-cloud-firestore.adoc
> +|Tets the emulator host to use with this Firestore client.
Fixed

2022-09-28 11:39 UTC, hg-ms approved these changes

2022-09-29 08:18 UTC, rdebusscher approved these changes
looks good

2022-09-29 08:58 UTC, merged